### ISSUE TITLE
Messages features no longer work

### ISSUE THREAD

**Issue by hubert-lang** [DinoDevs/GladiatusCrazyAddon#392] opened 2022-07-27 01:43 UTC
Message tab looks the same like w/out GCA

**Comment by GramThanos** [comment] 2022-07-27 03:16
Possible duplicate of #382

**Comment by FrutyX** [comment] 2022-07-27 04:29
This is a known issue that already has been reported in #382, thus this is a duplicate.

Closing.

**Closed by FrutyX** 2022-07-27 04:29 UTC
