### ISSUE TITLE
Target list add button doesn't show on cross arena players

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#224] opened 2020-09-26 12:55 UTC
The target list add button doesn't show up on players from other servers (at least for some players)

**Comment by GramThanos** [comment] 2020-10-10 21:42
The problem is that the `document.referrer` is no longer caring the URL parameters, thus the new script can not retrieve the secure hash.

**Comment by GramThanos** [comment] 2020-12-10 13:00
Walk-around was implemented.
Fixed on cb84f9fd6dc156905737501ed69a6be83acb18a7

**Comment by GramThanos** [comment] 2021-03-11 17:53
New version is out, closing this one for now.

**Closed by GramThanos** 2021-03-11 17:53 UTC
Labels: :beetle: bug, :mag: testing, :seedling: patched
