### ISSUE TITLE
Package items disappear on item move (problematic pages loading)

### ISSUE THREAD

**Issue by Ondraczz3** [DinoDevs/GladiatusCrazyAddon#471] opened 2024-06-06 00:14 UTC

**Comment by Ondraczz3** [comment] 2024-06-06 00:18
https://github.com/DinoDevs/GladiatusCrazyAddon/assets/165718681/ac8dd3f4-151d-45ab-b45e-f9ed918a9a8f

**Comment by GreatApo** [comment] 2024-06-06 17:44
Can you please describe the issue? I can't tell what problem you show in the video.

**Comment by FrutyX** [comment] 2024-06-06 18:20
@GreatApo The items, the moment he moves one, the others change, some disappear, am I seeing it right?

**Comment by GreatApo** [comment] 2024-06-06 18:23
> @GreatApo The items, the moment he moves one, the others change, some disappear, am I seeing it right?

Omg, I must be blind...

**Comment by FrutyX** [comment] 2024-06-06 18:25
It's fine Apo, I did not see it the first time either.

**Comment by FrutyX** [comment] 2024-06-07 17:57
We dont have much info here, I can't reproduce this...

**Comment by GramThanos** [comment] 2024-06-07 18:30
There is no fix for that, we are doing the best we can without generating server traffic.

**Comment by FrutyX** [comment] 2024-06-07 22:13
Thanos said and so it shall be.

**Comment by GreatApo** [comment] 2024-06-08 14:45
I would just leave it open in case a better approach comes up

**Comment by FrutyX** [comment] 2024-06-11 16:20
That's all nice, but has anyone actually managed to reproduce this? Because I for sure didn't.

**Comment by GramThanos** [comment] 2024-06-11 20:44
Let me explain the problem.

Gladiatus has 1 API to fetch 1 item from the next packages page so that it can appear and fill in the position when you move items from your packages to your bag. So the flow is:

1. move a package to your bag
2. request was processed and move finished 
3. retrieve the item that will fill the spot

And here is the problem, GCA allows you to move items from packages to your bag fast. So the flow ends up being:

1. move package A to your bag
2. move package B to your bag
3. request for package A finished
4. request for package B finished
5. retrieve the next item (which now is not the next, is the one after the next since 2 items were moved)
6. retrieve the next item (which may be the same as on step 5, thus will not be shown)

**Comment by FrutyX** [comment] 2024-06-11 22:06
<details>

![bruh](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/23278552/f9773c8b-59d7-4c25-8d52-09accf4c3e1c)

</details>

**Comment by GramThanos** [comment] 2024-09-15 16:37
I am closing this. If more info are given we can look into it again.

**Closed by GramThanos** 2024-09-15 16:37 UTC
Labels: :bug: bug, :raised_hand: help wanted, 🚫 wontfix
