### ISSUE TITLE
[Bug] Auction sort healing bug

### ISSUE THREAD

**Issue by FacMaster** [DinoDevs/GladiatusCrazyAddon#216] opened 2020-09-04 16:03 UTC
Healing is "Curación" in Spanish.

[https://prnt.sc/ubmlu1](https://prnt.sc/ubmlu1)

**Comment by FrutyX** [comment] 2021-12-16 00:45
If you don't mind, I'll close this, the reason? Not enough info, no further response, no possibility to reproduce and there may be other circumstances.

Create a new Issue with more info if you are still having this problem.

![bugfreee](https://user-images.githubusercontent.com/23278552/146286055-8deed241-6e62-4824-8f82-7c305e275330.PNG)

![bugfree2](https://user-images.githubusercontent.com/23278552/146287205-a093c16d-4923-48fb-9539-d9d032cd75b0.PNG)
![bugfree](https://user-images.githubusercontent.com/23278552/146287211-143f4ce4-e267-4832-8802-ec6f25799583.PNG)

**Closed by FrutyX** 2021-12-16 00:45 UTC
Labels: :mag: investigating
