### ISSUE TITLE
Pop bag over on scroll - Background 

### ISSUE THREAD

**Issue by Zitronenen** [DinoDevs/GladiatusCrazyAddon#273] opened 2021-07-17 21:05 UTC
**Describe the bug**
The Filter of the "Pop bag" need an other Background
Screenshot from the UW, but its the same thing at Expedition:
![Screenshot_1](https://user-images.githubusercontent.com/8767665/126036792-1658b4fb-889f-445b-99c1-e893eee00989.png)

**Comment by FrutyX** [comment] 2021-07-17 22:22
What browser are you using? On Firefox, I've noticed that some backgrounds are not getting loaded sometimes.

Also, did you disabled any Adblock/uBlock?

This is on Google Chrome:

![gca](https://user-images.githubusercontent.com/23278552/126050523-067ab463-91ad-43b7-a535-49a2d903ade2.PNG)

**Comment by Zitronenen** [comment] 2021-07-17 22:28
Hello @FrutyX 

i used Version 91.0.4472.164 (Offizieller Build) (64-Bit) of Google Chrome.
Ublock is for test inactiv. 
Cache cleared.

**Comment by FrutyX** [comment] 2021-07-18 14:21
UW:

![uw](https://user-images.githubusercontent.com/23278552/126069211-5e0c19e9-41c0-414e-8ae2-93c2dcc12e02.PNG)

Hmm, same browser, same version and yet I don't have this problem.

Maybe you could check the browser's console? Press F12 and go to the site with packages, view it, and see it there is any error, they are red (some errors can be from uBlock, so turn him off), if yes, then copy it here.

**Comment by Zitronenen** [comment] 2021-07-18 16:28
I hope i am right. 
My F12 Console show me this:
![Screenshot_1](https://user-images.githubusercontent.com/8767665/126074894-ff8c9e4c-f357-4177-97e8-a28104fc576c.png)

**Comment by FrutyX** [comment] 2021-07-18 16:51
Hmm, then I am not sure what is causing this.

Could be a difference between our GCA settings, I have almost everything enabled.

Maybe Thanos will know more.

**Comment by GreatApo** [comment] 2021-07-18 19:55
Is it happening only on underworld?

**Comment by FrutyX** [comment] 2021-07-18 23:24
If you check his screenshot with the console, you can clearly see, that the problem is here and the background is not the underworld one :D :)

**Comment by FrutyX** [comment] 2021-07-18 23:36
Okay boys, I have successfully reproduced this problem, it's in the settings.

When this is set to OFF, the inventory settings got no background:

![setting](https://user-images.githubusercontent.com/23278552/126085534-baa418e8-fb9c-41f1-bc3d-5e2d66932f69.PNG)
**=**
![gcabug](https://user-images.githubusercontent.com/23278552/126085538-2d034ad7-435b-40b2-80ae-f82f22f7753b.PNG)

**Comment by Zitronenen** [comment] 2021-07-19 02:12
I can now also confirm. =)
![Screenshot_3](https://user-images.githubusercontent.com/8767665/126093072-c43f58f0-f9a4-4016-8547-ccc3039c4979.png)

Thank you @FrutyX

**Comment by Zitronenen** [comment] 2021-07-19 15:20
Sorry for Off Topic.
@FrutyX can u contact me at https://forum.gladiatus.gameforge.com/user/3386-flamingo/?

**Comment by GramThanos** [comment] 2021-07-19 15:40
He wants to buy food items.

**Comment by Zitronenen** [comment] 2021-07-19 15:45
Hehe yeah @FrutyX  But no I need something for the documentation, I know =)

**Comment by FrutyX** [comment] 2021-07-19 17:58
@GramThanos Don't you have some issues to solve? Hehehehe 😃 

@Zitronenen I've contacted you on the forums.

**Comment by GramThanos** [comment] 2021-07-19 18:01
@FrutyX nope

**Comment by GramThanos** [comment] 2021-08-28 17:29
@FrutyX Don't you have some testing todo? 😆

**Comment by FrutyX** [comment] 2021-08-28 20:33
Oh, look who woke up :)

Tested, fixed, nicely done!

**Comment by Zitronenen** [comment] 2021-08-28 21:35
Thank you for the fix =)

**Comment by GramThanos** [comment] 2021-08-28 21:37
I will leave it open untill we log this, coz I will forget it.

**Comment by FrutyX** [comment] 2021-12-13 22:10
Fixed and already on the list, closing.

Re-open if needed.

**Closed by FrutyX** 2021-12-13 22:10 UTC
Labels: :bug: bug, :seedling: patched
