### ISSUE TITLE
Quests no longer sort

### ISSUE THREAD

**Issue by hubert-lang** [DinoDevs/GladiatusCrazyAddon#391] opened 2022-07-27 01:41 UTC
the quests list looks exactly the same as without the GCA

when you are outside Pantheon tab the yellow text "(New)" is still displayed next to the tab name "Pantheon" regardless quest time status

therefore the timer is no longer displayed too

![image](https://user-images.githubusercontent.com/60967360/181141892-84865d21-9e4e-4cc1-9996-bbc129b46b07.png)
![image](https://user-images.githubusercontent.com/60967360/181141950-3bbb15e3-591f-46a9-91da-58bb7f63caed.png)

**Comment by GramThanos** [comment] 2022-07-27 03:16
Possible duplicate of #382

**Comment by FrutyX** [comment] 2022-07-27 04:29
This is a known issue that already has been reported in #382, thus this is a duplicate.

Closing.

**Closed by FrutyX** 2022-07-27 04:29 UTC
