### ISSUE TITLE
Settings for missing feature

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#269] opened 2021-05-27 23:19 UTC
Apparently, the following setting:
![image](https://user-images.githubusercontent.com/9620510/119908345-48839480-bf4a-11eb-9a6b-8af9ab74acbc.png)

enables, this:
![image](https://user-images.githubusercontent.com/9620510/119908384-5afdce00-bf4a-11eb-8f8b-0ed3ebd915a1.png)
![image](https://user-images.githubusercontent.com/9620510/119908365-51746600-bf4a-11eb-87ba-4f1b15a09bea.png)

**Comment by FrutyX** [comment] 2021-05-29 15:03
Ahahahah, I mean, sorry, I could not help myself :D :D.

![dinodevs](https://user-images.githubusercontent.com/23278552/120075000-c9a07000-c09f-11eb-9bb1-aaeed21086aa.jpg)

**Comment by GramThanos** [comment] 2021-05-29 15:49
I am considering the possibility of creating a bot to automate this hahaha

**Comment by FrutyX** [comment] 2021-09-14 20:42
This is it, isn't it? But maybe I am too fast for you and not letting you finish your stuff :D

![Výstřižek](https://user-images.githubusercontent.com/23278552/133330820-275c04b9-ed87-46c3-bb23-c1de1a264a36.PNG)

**Comment by GramThanos** [comment] 2021-09-14 21:51
Re-patched.

**Comment by FrutyX** [comment] 2021-09-14 22:08
Good, normal translated text is back, we good here 👍.

**Comment by Zitronenen** [comment] 2021-09-20 20:02
Was that the "Enable Send Messages Box" feature?
Has that been completely removed?

**Comment by GramThanos** [comment] 2021-09-20 21:42
It was just an idea, not implemented.
The idea was to add a message box at the top of the messages page and also maybe auto load new messages on the list, so that it is more like a chat.

**Comment by Zitronenen** [comment] 2021-09-20 23:14
Thank you for  explaining me.
I will change the documentation ... Soon =)

**Comment by FrutyX** [comment] 2021-09-21 02:28
You know, the idea itself isn't bad at all, the problem is, that Gladiatus has an live chat and no one is using it. Only thing that sounds  useful and could be interesting is the auto load thing, auto-refresh so you see new incoming messages without refreshing the page (for writing you can use the box in quick menu), but that would require some work, because you don't want to refresh the whole page, but only specific part of the page, which could get a bit tricky (I guess).

**Comment by Zitronenen** [comment] 2021-09-21 03:34
But if I play active gladiatus so there you click many times in the minute (Speedserver). The automatic loading is also unnecessary. Or are you writing there without playing? =)

**Comment by FrutyX** [comment] 2021-09-21 03:48
Actually yea, there was a few situations where I was just talking to my guildmates without playing much. But we don't want to waste Gram's time, this "idea" has no priority at all.

**Comment by FrutyX** [comment] 2021-12-13 22:09
Cleaned and on the list, closing.

**Closed by FrutyX** 2021-12-13 22:09 UTC
Labels: :bug: bug, :seedling: patched
