### ISSUE TITLE
Missing drop materials

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#393] opened 2022-07-28 12:27 UTC
I am getting such an error. Raw materials are not visible under the items.

![image](https://user-images.githubusercontent.com/95325400/181504575-f73440c8-0175-4a63-ab0b-b41d0d00cba4.png)

**Comment by GramThanos** [comment] 2022-07-28 12:55
Duplicate of #382

**Closed** 2022-07-28 14:24 UTC
Labels: :hamster: :hamster: duplicate
